version: '3.9'

networks:
  poseidon_network:
    external: true
  portunus_network:
    external: true

services:
  cerberus_api:
    env_file:
      - .env
    image: cerberus_api:latest
    networks:
      - portunus_network
      - poseidon_network

  cerberus_web:
    image: cerberus_web:latest
    networks:
      - poseidon_network

  keto:
    image: oryd/keto:latest
    networks:
      - portunus_network
      - poseidon_network
    volumes:
      - type: bind
        source: ./config/keto
        target: /home/ory

