version: '3.9'

networks:
  poseidon_network:
    external: true
  portunus_network:
    external: true

services:
  cerberus_api:
    env_file:
      - ./config/cerberus/.env
    image: cerberus_api:latest
    networks:
      - portunus_network
      - poseidon_network
    ports:
      - 8911:8911

  cerberus_web:
    image: cerberus_web:latest
    networks:
      - poseidon_network
    ports:
      - 8910:8910

  keto:
    image: oryd/keto:latest
    networks:
      - portunus_network
      - poseidon_network
    volumes:
      - type: bind
        source: ./config/keto
        target: /home/ory

