version: '3.9'

networks:
  poseidon_network:
    external: true
  portunus_network:
    external: true

services:
  cerberus_api:
    env_file:
      - .env
    image: cerberus_api:latest
    networks:
      - portunus_network
      - poseidon_network

  cerberus_web:
    image: cerberus_web:latest
    networks:
      - poseidon_network
    volumes:
      - web_config:/data
      - web_data:/config

  keto:
    image: oryd/keto:v0.6.0-alpha.3
    networks:
      - portunus_network
      - poseidon_network
    volumes:
      - ./config/keto:/home/ory

volumes:
  web_config:
  web_data: