version: '3.9'

networks:
  default:
    driver: overlay
    name: cerberus_network
  poseidon_network:
    external: true
  portunus_network:
    external: true

services:
  access:
    image: oryd/keto:latest
    networks:
      - default
      - portunus_network
      - poseidon_network # FIXME: remove in production
    volumes:
      - type: bind
        source: ./config/keto
        target: /home/ory

  # Mailslurper is NOT for production use.
  #
  # Useful for development-time testing of Cerberus' functionality
  # To use, set the environment variable `SMTP_HOST` to 'localhost' and `SMTP_PORT` to `2500`.
  # Both `SMTP_USER` and `SMTP_PASS` can be left blank.
  # You can view the emails sent at http://localhost:8080
  mailslurper:
    image: marcopas/docker-mailslurper:latest
    ports:
      - '8080:8080'
      - '8085:8085'
      - '2500:2500'
    networks:
      - default
