# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = "Cerberus"
  host = "127.0.0.1"
  includeEnvironmentVariables = ['API_URL', 'BRAND_URL', 'PRIVACY_URL', 'SUPPORT_URL', 'WEB_URL']
  port = 8910
  apiProxyPath = "/.redwood/functions" # "/api"
[api]
  host = "127.0.0.1"
  port = 8911
[browser]
  open = true
[experimental]
  esbuild = false
  useEnvelop = false
[generate]
  tests = false
  stories = false
