# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  includeEnvironmentVariables = ['BRAND_URL', 'PRIVACY_URL', 'SUPPORT_URL']
  title = "Cerberus"
  apiProxyPath = "/cerberus/api"
  apiProxyPort = 8000
[api]
  port = 8911
[browser]
  open = true
[experimental]
  esbuild = false
  useEnvelop = false
[generate]
  stories = false
  tests = false
