export const createRole = jest.fn()
export const role = jest.fn()
export const roles = jest.fn()
export const updateRole = jest.fn()
export const deleteRole = jest.fn()
export const deleteAllRoles = jest.fn()
export const addPermToRole = jest.fn()
export const addRoleToAccount = jest.fn()
export const delPermFromRole = jest.fn()
export const delRoleFromAccount = jest.fn()

beforeEach(() => {
  createRole.mockClear()
  role.mockClear()
  roles.mockClear()
  updateRole.mockClear()
  deleteRole.mockClear()
  deleteAllRoles.mockClear()
  addPermToRole.mockClear()
  addRoleToAccount.mockClear()
  delPermFromRole.mockClear()
  delRoleFromAccount.mockClear()
})
